# ######################################################
## General

# Change board name
CONFIG_ZMK_KEYBOARD_NAME="T'scornes"

### Power
CONFIG_ZMK_SLEEP=y # Enable deep sleep support
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# ######################################################
## Split Keyboard (Cải thiện kết nối 2 nửa)
# Bật báo pin của nửa còn lại sang nửa chính
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# ######################################################
## OLED Display
CONFIG_ZMK_DISPLAY=y

# Dùng Work Queue riêng cho OLED để chống crash (Đặc biệt quan trọng trên nice!nano v2)
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Bật hiển thị các Widget cơ bản
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# Tắt tạm WPM vì cập nhật liên tục dễ gây lỗi nghẽn I2C nếu nguồn không ổn định
CONFIG_ZMK_WIDGET_WPM_STATUS=n

# Bật lại EXT_POWER (Nếu tắt, màn hình có thể bị mất điện nguồn)
CONFIG_ZMK_EXT_POWER=y
